name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ejecutar el flujo de trabajo cuando haya un push en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Publicar desde la raíz del repositorio
        publish_branch: main  # Publicar en la rama main
